GET https://notes-backend-kjkg.onrender.com/api/persons

###
POST https://notes-backend-kjkg.onrender.com/api/persons HTTP/1.1
Content-Type: application/json

{
    "name": "juul",
    "number": "666666"
}
###

DELETE https://notes-backend-kjkg.onrender.com/api/persons